server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  data:
    mongodb:
      uri: mongodb://test:test@localhost:27017/chord_play
  security:
    user:
      password: user
    oauth2:
      client:
        registration:
          google:
            client-id: 554846798235-uu5sm979htghi8ci43faasghshggsuom.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile


cloud:
  aws:
    credentials:
      access-key: xxx
      secret-key: xxx
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      queue:
        name: AiSheet.fifo
        url: 생성한 sqs 큐 url
jpa:
  hibernate:
    ddl-auto: create
properties:
  hibernate:
    show_sql: true
    format_sql: true
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: tra