spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: 1234
      database: chord_play
      port: 27017
      host: localhost
jpa:
  hibernate:
    ddl-auto: create
properties:
  hibernate:
    show_sql: true
    format_sql: true
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: tra