spring:
  data:
    mongodb:
      uri: mongodb://ec2-15-164-70-33.ap-northeast-2.compute.amazonaws.com:27017/chordplay
      username: baetles
      password: 1234
cloud:
  aws:
    credentials:
      access-key: xxx
      secret-key: xxx
    region:
      static: ap-northeast-2
    stack:
      auto: false
    sqs:
      queue:
        name: AiSheet.fifo
        url: 생성한 sqs 큐 url
jpa:
  hibernate:
    ddl-auto: create
properties:
  hibernate:
    show_sql: true
    format_sql: true
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: tra