spring:
  data:
    mongodb:
      uri: mongodb://ec2-54-180-119-145.ap-northeast-2.compute.amazonaws.com:27017/chordplay
      username: baetles
      password: 12345
cloud:
  aws:
    region:
      static: ap-northeast-2
    stack:
      auto: false
jpa:
  hibernate:
    ddl-auto: create
properties:
  hibernate:
    show_sql: true
    format_sql: true
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: tra