spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: password
      database: admin
      port: 27017
      host: localhost
jpa:
  hibernate:
    ddl-auto: create
properties:
  hibernate:
    show_sql: true
    format_sql: true
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: tra